apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp
  namespace: argocd
spec:
  project: default
  source:
    path: ./envs/staging/my-app
    plugin:
      #name: my-plugin-v1.0
      env:
        - name: ARGOCD_ENV_FOO
          value: toto
    repoURL: 'https://github.com/Abdellah91/appforargocd.git'
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'