apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp
  namespace: argocd
spec:
  project: default
  source:
    path: envs/staging/my-app
    plugin:
      env:
        - name: FOO
          value: toto
    repoURL: 'https://github.com/Abdellah91/appforargocd.git'
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'