apiVersion: v1
kind: ConfigMap
metadata:
  name: my-plugin-config
data:
  plugin.yaml: |
    apiVersion: argoproj.io/v1alpha1
    kind: ConfigManagementPlugin
    metadata:
      name: my-plugin
    spec:
      version: v1.0
      init:
        command: [sh, -c, 'echo ""']
      generate:
        command: [sh, -c, 'echo "{\"kind\": \"Namespace\", \"apiVersion\": \"v1\", \"metadata\": { \"name\": \"myns\"}}"']
      discover:
        fileName: "./README.md"