apiVersion: v1
kind: ConfigMap
metadata:
  name: my-plugin-config
data:
  plugin.yaml: |
    apiVersion: argoproj.io/v1alpha1
    kind: ConfigManagementPlugin
    metadata:
      name: my-plugin
    spec:
      version: v1.0
      init:
        command: [sh, -c, 'kustomize version']
      generate:
        command: [sh, -c, 'kustomize edit set image nginx=alpine && kustomize build .']
      discover:
        fileName: "./kustomization.yaml"